######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 18 17:54:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += link_pkgconfig
PKGCONFIG += xcomposite \
    xdamage

# Input
SOURCES += main.cpp
