syntax on
set nu

"状态栏标尺
set ru

"Taglist
"let Tlist_lnc_Winwidth=1
"
let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1
map <F7> :w <CR>: TlistToggle <CR>

set is
"
let g:winManagerWindowLayout = "FileExplorer" 

"默认情况下， 在 VIM 中当光标移到一行最左边的时候， 我们继续按左键， 光标不能回到上一行的最右边。 同样地， 光标到了一行最右边的时候，我们不能通过继续按右跳到下一行的最左边。 但是， 通过设置 whichwrap 我们可以对一部分按键开启这项功能。
set whichwrap=b,s,<,>,[,]


"编辑时，所有Tab替换为空格
if( expand("%:t") != "Makefile")
    "自动缩进为4个空格
    set sw=4
    "Tab 宽度为4个字符
    set ts=4
    set et
else "Makefile需要Tab键不为空
    set sw=8
    set ts=8
endif

"单词不分行显示
set lbr

" 括号配对
" set sm

"保持粘贴格式
set paste

"c/c++风格
" V选中一段文本，=调整文本格式
set cin
"据说是c/c++风格自动缩进选项
set cino=:0g0t0(sus 

"设置编码
set encoding=utf-8
set fileencodings=utf-8,chinese
if has("win32")
    set fileencoding=chinese
else
    set fileencoding=utf-8
endif
let &termencoding=&encoding

map <F2> :call ToggleSketch() <CR>

"保存退出的位置
if has("autocmd")
    autocmd BufRead *.txt set tw=78
    autocmd BufReadPost *
        \ if line("'\"") > 0 && line ("'\"") <= line("$") |
        \ exe "normal g'\"" |
        \ endif
endif

"no bell
set vb t_vb=


"
map <F8> :<Esc>:w <CR>:WMToggle<CR>
map <F5> :w <CR>:make <CR>

"多个文件被编辑时，<F4>显示标签
map <F4> :ls <CR>:e #

"当前文件没有被保存也可以切换到其他标签
set hidden


"
set tags=tags

"
filetype plugin on 
filetype plugin indent on

" 插入函数注释模板
" map <F3> \cfu 

"搜索中乎略大小写
"set ignorecase

"自动补全-3个字符后
"autocmd BufEnter * call DoWordComplete()

" 高亮搜索
set hlsearch

"使用desert.vim配色
colorscheme desert
"colorscheme darkblue
"vim: sw=4 ts=4    

set cspc=100

"===================
"vala start settings
"===================
autocmd BufRead *.vala set efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
autocmd BufRead *.vapi set efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
au BufRead,BufNewFile *.vala            setfiletype vala
au BufRead,BufNewFile *.vapi            setfiletype vala

" Disable valadoc syntax highlight
"let vala_ignore_valadoc = 1

" Enable comment strings
let vala_comment_strings = 1

" Highlight space errors
let vala_space_errors = 1
" Disable trailing space errors
"let vala_no_trail_space_error = 1
" Disable space-tab-space errors
let vala_no_tab_space_error = 1

" Minimum lines used for comment syncing (default 50)

"美化代码
map <C-F8> :w<CR>:!astyle --style=ansi -c -F -n %<CR><Enter>:vi %<CR>

" For vimwiki
" set nocompatible
let g:vimwiki_list = [{'path': '~/.vim/my_site/', 'path_html': '~/.vim/public_html/'}]


" 禁止报警闪烁
set novisualbell
